### ISSUE TITLE
Status / console bar is not resizable

### ISSUE THREAD

**Issue by barryknobel** [pycom/pymakr-atom#92] opened 2018-08-15 08:36 UTC
The Status / console bar at the bottom of the screen is not resizable.

![screen shot 2018-08-15 at 10 35 29](https://user-images.githubusercontent.com/10732361/44139309-fed292d6-a076-11e8-9415-c8bb069610f7.png)

**Comment by RalphHogenbirk** [comment] 2018-08-27 13:06
@barryknobel Thanks for reporting, which OS and which Atom/Pymakr versions are you using? I've seen this before, but only on linux, and I haven't been able to reproduce it.

**Comment by lemariva** [comment] 2018-09-10 19:57
I have/had the same problem. Atom: 1.30 Pymakr: 1.4.2 OS: Windows 10
Solution: if you disable the atom-ide-ui package, the console goes back to the right size.

**Comment by tmmorin** [comment] 2019-03-17 16:35
I have the same issue (pymakr  1.4.11, atom 1.35.1 on Linux).
The same workaround works for me as well.
It would be great to have pymakr work out of the box, though...

**Comment by stevempotter** [comment] 2019-03-18 17:41
@RalphHogenbirk, 
I was frustrated by this bug also. I am using Mac 10.13.6 and Atom 1.35.1 and pymakr package 1.4.12.
I note that I had to res
![Screen Shot 2019-03-18 at 17 29 57](https://user-images.githubusercontent.com/5586932/54551017-1149ee00-49a5-11e9-9c62-4cbba87a3ea3.png)
tart Atom after disabling the atom-ide-ui package in order to be able to see more than one line of my connection pane.

**Comment by pedroknup** [comment] 2020-02-18 15:50
Fixed on Pymakr 2.0

**Closed by pedroknup** 2020-02-18 15:50 UTC
Labels: question
