### ISSUE TITLE
Can't connect to LoPy!!

### ISSUE THREAD

**Issue by msomi22** [pycom/pymakr-atom#27] opened 2017-06-28 12:19 UTC
Failed to connect (Error: Error: Broken pipe, cannot drain)

**Comment by RalphHogenbirk** [comment] 2017-06-28 12:23
Duplicate of closed issue #26. Solution is build in on the develop branch. You can either temporarily downgrade to 1.0.1 or upgrade to the code on develop. New version including this fix can be expected end of this week.

**Comment by RalphHogenbirk** [comment] 2017-07-06 09:52
Fixed with the latest release 1.0.3. Can you confirm @msomi22?

**Closed** 2017-07-21 12:35 UTC
