### ISSUE TITLE
Connection timeout when device is in a loop

### ISSUE THREAD

**Issue by rbraggaar** [pycom/pymakr-atom#2] opened 2017-04-13 17:40 UTC
My Lopy is setup to read sensor values and print them in a loop.
Apparently this hinders the REPL console from recognizing the password option.

![timeout](https://cloud.githubusercontent.com/assets/16044244/25016597/fd349432-2080-11e7-8a5e-9cb296163fea.PNG)

No problems in Putty.

**Comment by RalphHogenbirk** [comment] 2017-04-14 08:11
As we already discussed on the forum, this problem is not due to the device being in a loop, since signin and micropython run on 2 different threads. Ofcourse it could be that there is a bug in the plugin itself where it can end up in this state. 

Is it solved when you reboot both the device and atom? Any specific order of actions you could give to reproduce the problem, or does it already appear when connecting after startup?

**Comment by danicampora** [comment] 2017-04-14 10:58
Hi Rob,

Could you please share a pice of code running on the LoPy/WiPy that reproduces the issue. That way we can test it and solve it. Thanks!

Cheers,
Daniel

**Comment by rbraggaar** [comment] 2017-04-14 12:34
I now removed the code from the Lopy but the problem is still the same. 

My steps:
I power the Lopy
Connect to its WLAN
Open Atom (it will start connecting and fail)

Reopening Atom doesn't help, neither does resetting the Lopy (or both)
It connected once for me, on Atom startup yesterday whereafter it dropped the connection and refuses to connect again.

**Comment by RalphHogenbirk** [comment] 2017-04-26 14:36
@rbraggaar After some testing I found out that when connecting on telnet to the local, the nodejs code is too fast with sending the password to the board, after it received the boards request to send it. It only happens sometimes with my board, and connecting through the router works fine.

I just pushed a fix to the develop branch which you can test if you want. Let me know if this fixes your issue.

**Comment by rbraggaar** [comment] 2017-04-30 18:34
Now works good for me, tested on Wipy and Lopy.

**Comment by RalphHogenbirk** [comment] 2017-05-01 07:26
Good to hear! I'll to a merge to master soon

**Closed by RalphHogenbirk** 2017-05-01 07:26 UTC
